language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda update -q conda
  - conda info -a
#  - conda env create -f ./config/travis_CI/environment.yml
  - conda env create environment.yml
  - source activate geo_deep_env

before_script:
  - unzip ./data/massachusetts_buildings.zip -d ./data
  - unzip ./data/classification_data.zip -d ./data
script:
  # sampling segmentation base on ./config/gdl_config_template.yaml
  - python GDL.py mode=sampling
  # sampling segmentation base on ./config/gdl_config_template.yaml
  - python GDL.py mode=train
  # sampling segmentation base on ./config/gdl_config_template.yaml
  - python GDL.py mode=inference
  
