name: gpu_ENV
channels:
- conda-forge
- fastai
- defaults
dependencies:
- python=3.6.11
- pip=20
- h5py==2.10.0
- fiona==1.8.13
- rasterio==1.1.5
- tqdm==4.48.2
- pytorch==1.3.1
- torchvision==0.4.2
- ruamel_yaml==0.15.80

- geopandas==0.8.1
- scikit-image==0.17.2
- scikit-learn==0.23.2
- nvidia-ml-py3==7.352.0
- mlflow==1.10.0