# @package _global_
callbacks:
  early_stopping:
    class_name: pl.callbacks.EarlyStopping
    params:
      monitor: ${training.metric}
      patience: 20
      mode: ${training.mode}
  model_checkpoint:
    class_name: pl.callbacks.ModelCheckpoint
    params:
      monitor: ${training.metric}
      save_top_k: 3
      dirpath: saved_models/
      mode: ${training.mode}