# Deep learning configuration file ------------------------------------------------
# Four sections :
#   1) Global parameters; those are re-used amongst the next three operations (sampling, training and classification)
#   2) Sampling parameters
#   3) training parameters
#   4) Classification parameters

# Global parameters

global:
  samples_size: 256
  num_classes: 2
  data_path: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_building_only
  input_images_band_count: 3

# Sample parameters; used in images_to_samples.py -------------------

sample:
  prep_csv_file: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_building_only/building_all.csv
  samples_dist: 200
  remove_background: True
  mask_input_image: False

# Training parameters; used in train_model.py ----------------------

training:
  output_path: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_building_only
  num_trn_samples: 4960
  num_val_samples: 2208
  pretrained: False # .pth filename containig pre-trained weights
  batch_size: 32
  num_epochs: 150
  learning_rate: 0.0001
  weight_decay: 0
  step_size: 4
  gamma: 0.9
  # class_weights: [1.0, 2.0, 2.0, 2.0]
  class_weights: [1.0, 2.0]

# Classification parameters; used in image_classification.py --------

classification:
  working_folder: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_building_only/tst
  model_name: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_building_only/tst/checkpoint.pth.tar
