# Job configuration file ------------------------------------------------
# Parameters used to dynamically generate for the shell script
# fed as an argument to the 'jobsub' command
# Variable strings ($...) in parameters are meant to be filled at run time

user_home: /fs/vnas_Hnrcan/geobase/yvm001
script_location: ap # with respect to user_home above
operation_config_location: ap/conf # with respect to user_home above
config_filename: config.yaml # Must be in 'operation_config_location' above
job_name: nrcan-interactive
dash_m: bea
user_email: NRCan.production_cits-production_cits.RNCan@canada.ca
join_stdout_err: y
output_file: /fs/vnas_Hnrcan/geobase/yvm001/out/pytorch_$operation_test.out
shell_used: /bin/bash
wallclock_time: 72:00:00
parallel_envs: gpu 1
res_cpus: 4
res_mem: 96000
res_image: nrcan_all_default_ubuntu-14.04-amd64_latest
res_gputype: k80
res_gpus: 1
python_envs: /space/hall0/sitestore/nrcan/geobase/opt/miniconda3/envs
default_env: AP_CCCOT
software_base: /fs/ssm/nrcan/geobase/tensorflow
work_base: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch
mkl_threading_layer: GNU
