# Deep learning configuration file ------------------------------------------------
# Four sections :
#   1) Global parameters; those are re-used amongst the next three operations (sampling, training and classification)
#   2) Sampling parameters
#   3) training parameters
#   4) Classification parameters

# Global parameters
global:
  samples_size: 128
  num_classes: 4

# Sample parameters; used in images_to_samples.py -------------------
sample:
  images_folder: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_training/val
  samples_folder: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_training/val/samples
  samples_dist: 100

# Training parameters; used in train_model.py ----------------------
training:
  data_path: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_training
  output_path: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_training
  num_trn_samples: 38400
  num_val_samples: 19200
  pretrained: False # .pth filename containig pre-trained weights
  batch_size: 96
  num_epochs: 150
  learning_rate: 0.001
  weight_decay: 0
  step_size: 30
  gamma: 0.1
  class_weights: [1.0, 2.0, 2.0, 2.0]


# Classification parameters; used in image_classification.py --------
classification:
  working_folder: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_training/tst/RGB
  model_name: /space/hall0/work/nrcan/geobase/extraction/Deep_learning/pytorch/data_training/last_epoch.pth.tar

# Other params --------------------------------------
# ALL ITEMS LISTED NEXT NOT USED YET
learning_rate_schedule:
    init: 0.1
    final: 0.0001

momentum_schedule:
    0: 0.0
    1: 0.5
    2: 0.9

layer_config:
    0:
        layer_type: InputLayer
        input_shape: [128, 1, 91, 64]

    1:
        layer_type: Conv2DLayer
        n_filters: 64
        filter_size: [8,59]
        nonlinearity: rectifier
        init_bias_value: 0.01

    2:
        layer_type: MaxPooling2DLayer
        pool_size: [6,3]
        ignore_border: False

    3:
        layer_type: DenseLayer
        n_outputs: 500
        nonlinearity: rectifier
        init_bias_value: 0.1
        dropout: 0.5

    4:
        layer_type: DenseLayer
        n_outputs: 2
        nonlinearity: sigmoid
        init_bias_value: 0.1
        dropout: 0.0

    5:
        layer_type: OutputLayer
