# Deep learning configuration file ------------------------------------------------
# Five sections :
#   1) Global parameters; those are re-used amongst the next three operations (sampling, training and inference)
#   2) Data analysis parameters
#   4) Sampling parameters
#   5) Training parameters
#   6) Inference parameters
#   7) Model parameters

# Global parameters

global:
  samples_size: 256
  num_classes: 4 
  data_path: /home/cauthier/data/ # TODO: put it in the git ignor
  number_of_bands: 4
  modalities: RGBN
  # Model must be in the follow list:
  # unet, unetsmall, checkpointed_unet, ternausnet,
  # fcn_resnet101, deeplabv3_resnet101
  model_name: deeplabv3_resnet101
  bucket_name:   # name of the S3 bucket where data is stored. Leave blank if using local files
  task: segmentation  # Task to perform. Either segmentation or classification
  num_gpus: 2
  aux_vector_file: 
  aux_vector_dist_map: False
  scale_data: [0,1]
  debug_mode: True

  #####
  # Module to include the NIR (temporary)
  # 1:'conv1',
  # 4:'after the maxpooling',
  # 6:'after the layer 2',
  # 7:'after the layer 3',
  # 8:'after the layer 4 (after the backbone)',
  # 9:'after the ASPP module'
  concatenate_depth: 1
  #####
  
# Data analysis parameters; used in data_analysis.py ------------------

data_analysis:
  create_csv: False
  optimal_parameters_search : False
  sampling: {'method':['min_annotated_percent', 'class_proportion'], 'map': 0, '0':0, '1':0, '2':0}
  # 'method' : One or both in any order of min_annotated_percent, class_proportion; must be presented in list format
    # 'map' : Min % of non background pixels in stored samples. Default: 0
    # following keys:
      # keys must be all classes present in the images
      # keys must be numerical values in 'string' format
      # class value must be in 'integer' format
      # class value represent class minimum threshold targeted in samples

# Sample parameters; used in images_to_samples.py -------------------

sample:
  prep_csv_file: /home/cauthier/data/test4channel.csv # TODO: put in git ignor
  val_percent: 5 # Percentage of validation samples created from train set (0 - 100)
  overlap: 25
  sampling: {'method':['min_annotated_percent'], 'map': 0, '0':0, '1':0, '2':0} # One of class_proportion, annotated_percent
    # 'method' : One or both in any order of min_annotated_percent, class_proportion; must be presented in list format
    # 'map' : Min % of non background pixels in samples. Default: 0
    # following keys:
      # keys must include all classes present in the images
      # keys must be numerical values in 'string' format
      # class value must be in 'integer' format
      # class value represents class minimum threshold targeted in samples

  mask_reference: False


# Training parameters; used in train_segmentation.py ----------------------

training:
  state_dict_path: #path/to/pretrained/file/checkpoint.pth.tar (optional)
  num_trn_samples: 4960
  num_val_samples: 847
  num_tst_samples: 1000
  batch_size: 4
  num_epochs: 1
  loss_fn: Lovasz # One of CrossEntropy, Lovasz, Focal, OhemCrossEntropy (*Lovasz for segmentation tasks only)
  optimizer: adabound # One of adam, sgd or adabound
  learning_rate: 0.0001
  weight_decay: 0
  step_size: 4
  gamma: 0.9
  dropout: False    # (bool) Use dropout or not
  dropout_prob:    # (float) Set dropout probability, e.g. 0.5
  class_weights: [1.0, 1.0, 1.0, 1.0,1.0]
  batch_metrics:    # (int) Metrics computed every (int) batches. If left blank, will not perform metrics. If (int)=1, metrics computed on all batches.
  ignore_index: -1 # Specifies a target value that is ignored and does not contribute to the input gradient. Default: None
  augmentation:
    rotate_limit: 45
    rotate_prob: 0.5
    hflip_prob: 0.5
  normalization:  # Normalization parameters for finetuning (Ex. mean: [0.485, 0.456, 0.406], std: std: [0.229, 0.224, 0.225])
    mean:
    std:

# Inference parameters; used in inference.py --------

inference:
  img_dir_or_csv_file: #/path/to/csv/containing/images/list.csv
  working_folder: #/path/to/folder/with/resulting/images
  state_dict_path: #/path/to/model/weights/for/inference/checkpoint.pth.tar
  chunk_size: 512 # (int) Size (height and width) of each prediction patch. Default: 512
  overlap: 10 # (int) Percentage of overlap between 2 chunks. Default: 10

# Visualization parameters

visualization:
  vis_batch_range: [0,200,10] #start, finish, increment
  vis_at_checkpoint: True
  vis_at_ckpt_min_ep_diff: 0
  vis_at_ckpt_dataset: val # FIXME: Parameter adds confusion. To be removed. Default to val dataset.
  vis_at_init: True
  vis_at_init_dataset: val
  vis_at_evaluation: True #val during training, tst at end of training
  vis_at_train: True
  grid: True
  heatmaps: True
  colormap_file: ./data/colormap.csv
