defaults:
  -hydra: default
  -task: segmentation # segmentation, object_detection, point_cloud, super_resolution
  -model: fastrcnn
  -trainer: default_trainer
  -training: default_training
  -optimizer: adamw
  -callbacks: default_callbacks
  -scheduler: plateau
  -sampling: default_sampling
  -data: data
  -dataset: NRCAN_individual_tree
  -augmentation: default_augmentation
  -logging: mlflow

general:
  project_name: template_project
  workspace: your_name
  device: cuda
  max_epochs: 10
  min_epochs: 1
  save_dir: './log'
  sample_data_dir: 'img/dir'
  save_weights_dir: './weights_saved'

inference:
  image_path: 'image/path'
  save_dir:
  weights_dir: ${general.save_weights_dir}
  weights_name:

mode: {sampling, train, evaluate, inference, hyperparameters_search}
debug: False # will print the complete yaml config plus run a validation test
