# @package _global_
verify:
  output_report_dir: /Users/abdielfer/RNCanWork/GDLData/
  output_raster_stats: False
  output_raster_plots: True
  extended_label_stats: True
  multiprocessing: False
  write_dest_raster: ${tiling.write_dest_raster}
