# @package _global_
dataset:
  name:
  modalities: RGB
  input_dim: 256
  overlap:
  min_annot_perc:
  raw_data_csv: ${general.raw_data_csv}
  raw_data_dir: ${general.raw_data_dir}
  sample_data_dir: ${general.sample_data_dir}
  class_name: src.utils.dataset.BaseDataSetObjectDetection
  classes_dict: {'Building':1}
  class_weights:
  train_val_percent: {'trn':0.7, 'val':0.2, 'tst':0.1}
  ignore_index:
  use_stratification: False

