# @package _global_
dataset:
  # dataset-wide
  name:
  raw_data_csv: /home/abfernan/CrossCanFloodMap/DatasetCNNFlood/RawData/Class1RawDataVelum.csv
  raw_data_dir: /home/abfernan/CrossCanFloodMap/DatasetCNNFlood/RawData/Class1
  download_data: False

  # imagery
  bands: [1]

  # ground truth
  attribute_field: percentage
  attribute_values: [1]
  class_name: # will follow in the next version
  classes_dict: {'FLood':1}
  class_weights:
  ignore_index: -1
